DROP TABLE IF EXISTS marketing_modeling.app_model_input_data;
CREATE TABLE IF NOT EXISTS `marketing_modeling.app_model_input_data`(
	  `mobile` string, 
	  `d_fir_leads_time` timestamp, 
	  `d_fir_sec_leads_diff` int, 
	  `d_leads_count` bigint, 
	  `d_avg_leads_date` double, 
	  `d_leads_dtbt_count` bigint, 
	  `d_leads_dtbt_coincide` double, 
	  `d_leads_dtbt_level_1` bigint, 
	  `d_cust_type` int, 
	  `d_fir_card_time` timestamp, 
	  `d_card_ttl` bigint, 
	  `d_fir_visit_time` timestamp, 
	  `d_visit_dtbt_count` bigint, 
	  `d_visit_ttl` bigint, 
	  `d_avg_visit_date` double, 
	  `d_avg_visit_dtbt_count` double, 
	  `d_fir_trail` timestamp, 
	  `d_last_reservation_time` timestamp, 
	  `d_trail_book_tll` bigint, 
	  `d_leads_car_model_count` bigint, 
	  `d_leads_car_model_type` bigint, 
	  `d_fir_dealfail_d` timestamp, 
	  `d_last_dealfail_d` timestamp, 
	  `d_is_deposit_order` int, 
	  `d_deal_flag` int, 
	  `d_avg_fircard_firvisit_diff` double, 
	  `d_activity_ttl` bigint, 
	  `d_followup_d7` bigint, 
	  `d_followup_d15` bigint, 
	  `d_followup_d30` bigint, 
	  `d_followup_d60` bigint, 
	  `d_followup_d90` bigint, 
	  `d_firlead_dealf_diff` int, 
	  `d_lastlead_dealf_diff` int, 
	  `d_last_dfail_dealf_diff` int, 
	  `d_lasttrail_dealf_diff` int, 
	  `d_leads_dtbt_ppt` double, 
	  `d_fircard_firvisit_diff` int, 
	  `c_trail_vel` string, 
	  `c_lead_sources` string, 
	  `c_last_activity_time` string, 
	  `c_lead_model` string, 
	  `c_sex` string, 
	  `c_age` string, 
	  `c_city` string, 
	  `h_loan` int, 
	  `h_model_nums` int, 
	  `h_have_car` int, 
	  `h_compete_car_num_d30` int, 
	  `h_compete_car_num_d60` int, 
	  `h_compete_car_num_d90` int, 
	  `h_focusing_avg_diff` int, 
	  `h_focusing_max_diff` int, 
	  `h_func_prefer` string, 
	  `h_car_type_prefer` string, 
	  `h_config_prefer` string, 
	  `h_budget` string, 
	  `h_level` string, 
	  `h_volume` string, 
	  `h_ttl_inquiry_time` int, 
	  `h_produce_way` string, 
	  `d_leads_dtbt_level_2` bigint, 
	  `d_fir_sec_visit_diff` int, 
	  `d_followup_ttl` bigint, 
	  `d_avg_fir_sec_visit_diff` double, 
	  `d_avg_firleads_firvisit_diff` double, 
	  `d_trail_count_d30` bigint, 
	  `d_visit_count_d15` bigint, 
	  `d_visit_count_d30` bigint, 
	  `d_visit_count_d90` bigint, 
	  `d_firfollow_dealf_diff` int, 
	  `d_dealf_firvisit_diff` int, 
	  `d_firleads_firvisit_diff` int, 
	  `c_register_time` int, 
	  `c_last_reach_platform` string
)
PARTITIONED BY (pt STRING COMMENT "datetime")
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
COLLECTION ITEMS TERMINATED BY ','
MAP KEYS TERMINATED BY ':'
STORED AS TEXTFILE;
;