
set hive.exec.dynamic.partition =true;
set hive.exec.dynamic.partition.mode = nonstrict;
INSERT INTO  marketing_modeling.app_big_wide_info_bak
SELECT
	mobile
,d_fir_leads_time
,d_last_leads_time
,d_fir_sec_leads_diff
,d_leads_count
,d_leads_channel
,d_avg_leads_date
,d_leads_channel_count
,d_leads_dtbt_count
,d_leads_dtbt_coincide
,d_leads_dtbt_level_1
,d_leads_dtbt_level_2
,d_cust_type
,d_fir_card_time
,d_last_card_time
,d_card_ttl
,d_cust_ids
,d_clue_issued_times
,d_fir_visit_time
,d_fir_sec_visit_diff
,d_visit_dtbt_count
,d_visit_ttl
,d_avg_visit_date
,d_dealer_ids
,d_avg_visit_dtbt_count
,d_followup_ttl
,d_fir_trail
,d_last_reservation_time
,d_trail_book_tll
,d_trail_attend_ttl
,d_trail_attend_ppt
,d_leads_car_model_count
,d_leads_car_model_type
,d_vel_series_ids
,d_series_types
,d_rw_car_model_count
,d_deal_time
,d_last_deal_time
,d_deal_ttl
,d_deal_car_ttl
,d_fir_dealfail_d
,d_last_dealfail_d
,d_is_deposit_order
,d_deal_flag
,d_leads_pool_status
,d_dealf_succ_firvisit_diff
,d_dealf_succ_lastvisit_diff
,d_avg_fir_sec_visit_diff
,d_fircard_firvisit_dtbt_diff
,d_avg_fircard_firvisit_diff
,d_avg_firleads_firvisit_diff
,d_fir_activity_time
,d_activity_ttl
,d_natural_visit
,d_fir_leads_deal_diff_y
,d_has_deliver_history
,d_trail_count_d30
,d_trail_count_d90
,d_visit_count_d15
,d_visit_count_d30
,d_visit_count_d90
,d_followup_d7
,d_followup_d15
,d_followup_d30
,d_followup_d60
,d_followup_d90
,d_activity_count_d15
,d_activity_count_d30
,d_activity_count_d60
,d_activity_count_d90
,d_firlead_dealf_diff
,d_lastlead_dealf_diff
,d_last_dfail_dealf_diff
,d_firfollow_dealf_diff
,d_lastfollow_dealf_diff
,d_dealf_lastvisit_diff
,d_dealf_firvisit_diff
,d_lasttrail_dealf_diff
,d_firleads_firvisit_diff
,d_leads_dtbt_ppt
,d_fircard_firvisit_diff
,d_fir_dealfail_deal_diff
,d_deal_fail_ppt
,d_last_activity_dealf_diff
,d_fir_activity_dealf_diff
,d_fir_order_leads_diff
,d_fir_order_visit_diff
,d_fir_order_trail_diff
,c_is_app_user
,c_brwose_count_d14
,c_avg_browse_time_d14
,c_last_app_visit_time
,c_app_point_ttl_d14
,c_app_point_ttl
,c_last_app_point_use_time
,c_is_trail_user
,c_trail_vel
,c_last_trail_vel
,c_deliver_vel
,c_visit_count
,c_visit_count_d14
,c_deal_time
,c_last_trail_time
,c_last_lead_time
,c_trail_count_d14
,c_last_reach_platform
,c_lead_sources
,c_last_bbs_time
,c_order_time
,c_last_sis_result
,c_open_link
,c_last_visit_time
,c_last_activity_time
,c_create_card_count
,c_cust_live_period
,c_followup_ttl
,c_last_sis_time
,c_deal_fail_time
,c_lead_model
,c_fail_status
,c_rx5_video_time
,c_marvel_video_time
,c_sex
,c_age
,c_province
,c_city
,c_last_lost_type
,c_last_lost_time
,c_roewe_brwose_homepage
,c_search_vel
,c_browse_model_info
,c_trail
,c_make_deal
,c_model
,c_register_time
,c_last_cust_base_time
,c_fail_real_result
,c_app_browse_count_d14
,h_goal
,h_loan
,h_priority_car_type
,h_configuration_preference
,h_priority_config_prefer
,h_priority_car_usage
,h_client_focus
,h_models
,h_model_nums
,h_have_car
,h_compete
,h_compete_car_num_d30
,h_compete_car_num_d60
,h_compete_car_num_d90
,h_focusing_avg_diff
,h_focusing_max_diff
,h_func_prefer
,h_car_type_prefer
,h_config_prefer
,h_budget
,h_displace
,h_level
,h_volume
,h_priority_change_car_and_buy
,h_ttl_inquiry_time
,h_max_inquiry_time
,h_produce_way
,h_config_nums
,h_leads_create_time
,s_firstleads_lastcard_call_count
,s_firstleads_firstcard_call_count
,s_avg_talk_length
,s_talk_connet_ppt
,s_first_call_result
,d_fail_desc_list
,d_fail_time_list
,d_cust_dealer_ids
,m_last_visit_time
,m_focus_series_count
,m_oppr_fail_count
,m_cust_max_level
,m_failed_called
,m_lead_source_count
,m_last_lead_first_source
,m_last_lead_second_source
,pt
FROM
	 marketing_modeling.app_big_wide_info
WHERE pt >='20200908'
;
