DROP TABLE IF EXISTS marketing_modeling.event_tmp; 
--创建事件表
create external table if not exists marketing_modeling.event_tmp(		
		id  bigint  COMMENT '{"columnName":"事件 id","columnDesc":"事件数据唯一id"}',	
		version  int  COMMENT  '{"columnName":"版本","columnDesc":"技术字段,使用默认中1即可"}',		
		anonymous_id  string  COMMENT  '{"columnName":"匿名Id","columnDesc":"微信中是 OpenId"}',
		channel_id  string COMMENT  '{"columnName":"渠道表中的channel_Id值","columnDesc":"渠道表中的channel_Id值"}',
		channel_name  string  COMMENT  '{"columnName":"渠道名称","columnDesc":"渠道标记名称"}',
		contact_identity_id  bigint  COMMENT  '{"columnName":"渠道账号 Id","columnDesc":"渠道账号 Id"}',
		context  string  COMMENT  '{"columnName":"上下文","columnDesc":"如是工作流触发的事件记录工作流 id"}',
		date_created  timestamp  COMMENT  '{"columnName":"数据创建时间","columnDesc":"数据创建时间，格式:时间戳"}',
		event  string  COMMENT  '{"columnName":"事件编号","columnDesc":"事件编号"}',
		event_date  timestamp  COMMENT  '{"columnName":"事件日期","columnDesc":"事件发生日期"}',
		event_id  string  COMMENT  '{"columnName":"事件 id","暂时用不到"}',
		last_updated  timestamp  COMMENT  '{"columnName":"数据最后修改时间","columnDesc":"初次跟date_created一致，格式:时间戳"}',
		property  string  COMMENT  '{"columnName":"事件原始信息","这里在暂时不用"}',
		tenant_id  bigint  COMMENT  '{"columnName":"租户id","columnDesc":"租户所属id"}',
		attr1  string  COMMENT  '{"columnName":"属性字段1","columnDesc":"属性字段1"}',
		attr2  string  COMMENT  '{"columnName":"属性字段2","columnDesc":"属性字段2"}',
		attr3  string  COMMENT  '{"columnName":"属性字段3","columnDesc":"属性字段3"}',
		attr4  string  COMMENT  '{"columnName":"属性字段4","columnDesc":"属性字段4"}',
		attr5  string  COMMENT  '{"columnName":"属性字段5","columnDesc":"属性字段5"}',
		attr6  string  COMMENT  '{"columnName":"属性字段6","columnDesc":"属性字段6"}',
		attr7  string  COMMENT  '{"columnName":"属性字段7","columnDesc":"属性字段7"}',
		attr8  string  COMMENT  '{"columnName":"属性字段8","columnDesc":"属性字段8"}',
		attr9  string  COMMENT  '{"columnName":"属性字段9","columnDesc":"属性字段9"}',
		attr10  string  COMMENT  '{"columnName":"属性字段10","columnDesc":"属性字段10"}',
		parent_id  bigint  COMMENT  '{"columnName":"父事件 Id","columnDesc":"columnDesc":"父事件 Id"}',
		attr11  string  COMMENT  '{"columnName":"属性字段11","columnDesc":"属性字段11"}',
		attr12  string  COMMENT  '{"columnName":"属性字段12","columnDesc":"属性字段12"}',
		attr13  string  COMMENT  '{"columnName":"属性字段13","columnDesc":"属性字段13"}',
		attr14  string  COMMENT  '{"columnName":"属性字段14","columnDesc":"属性字段14"}',
		attr15  string  COMMENT  '{"columnName":"属性字段15","columnDesc":"属性字段15"}',
		attr16  string  COMMENT  '{"columnName":"属性字段16","columnDesc":"属性字段16"}',
		attr17  string  COMMENT  '{"columnName":"属性字段17","columnDesc":"属性字段17"}',
		attr18  string  COMMENT  '{"columnName":"属性字段18","columnDesc":"属性字段18"}',
		attr19  string  COMMENT  '{"columnName":"属性字段19","columnDesc":"属性字段19"}',
		attr20  string  COMMENT  '{"columnName":"属性字段20","columnDesc":"属性字段20"}',
		sdk_version  string  COMMENT  '{"columnName":"SDK 版本","columnDesc":"SDK 版本"}',
		sdk_type  string  COMMENT  '{"columnName":"SDK 类型","columnDesc":"SDK 类型"}',
		platform  string  COMMENT  '{"columnName":"平台","columnDesc":"平台"}',
		screen_width  decimal(8, 4)  COMMENT  '{"columnName":"屏幕宽度","columnDesc":"屏幕宽度"}',
		screen_height  decimal(8, 4)  COMMENT  '{"columnName":"屏幕高度","columnDesc":"屏幕高度"}',
		app_version  string  COMMENT  '{"columnName":"app 版本","columnDesc":"app所属版本"}',
		bundle_key  string  COMMENT  '{"columnName":"绑定键值","columnDesc":"绑定键值"}',
		os  string  COMMENT  '{"columnName":"操作系统类型","columnDesc":"操作系统所属类型"}',
		os_version  string  COMMENT  '{"columnName":"操作系统版本","columnDesc":"操作系统所属版本"}',
		browser  string  COMMENT  '{"columnName":"浏览器","columnDesc":"浏览器类型"}',
		browser_version  string  COMMENT  '{"columnName":"浏览器版本","columnDesc":"浏览器所属版本"}',
		country  string  COMMENT  '{"columnName":"国家","columnDesc":"国家"}',
		province  string  COMMENT  '{"columnName":"省份","columnDesc":"省份"}',
		city  string  COMMENT  '{"columnName":"城市","columnDesc":"城市"}',
		network_type  string  COMMENT  '{"columnName":"网络类型","columnDesc":"网络类型"}',
		manufacturer  string  COMMENT  '{"columnName":"制造商","columnDesc":"制造商"}',
		device_model  string  COMMENT  '{"columnName":"设备类型","columnDesc":"设备类型"}',
		operator  string  COMMENT  '{"columnName":"操作","columnDesc":"操作"}',
		debug_mode  int  COMMENT  '{"columnName":"调试模式","columnDesc":"调试模式,默认1"}',
		imei  string  COMMENT  '{"columnName":"IMEI 号","columnDesc":"IMEI 号"}',
		ip  string  COMMENT  '{"columnName":"ip地址","columnDesc":"ip地址"}',
		latitude  decimal(9, 6)  COMMENT  '{"columnName":"经度","columnDesc":"经度"}',
		longitude  decimal(9, 6)  COMMENT  '{"columnName":"维度","columnDesc":"维度"}',
		trigger_flow  int  COMMENT  '{"columnName":"是否触发工作流","columnDesc":"无默认值"}',
		channel_app_id  bigint  COMMENT  '{"columnName":"所属渠道应用 id","columnDesc":"所属渠道应用 id"}'
    ) COMMENT '{"tableName":"记录自定义事件表","tableDesc":"用于记录自定义事件信息",
     "jiraInfo":"","developOwner":"向导","businessOwner":"郁雅婷" }'
	 partitioned by (pt string)
     row format delimited fields terminated by '\t' stored as orc
	 ;